import type { AdminHeroTemplateInput } from "@/api/types";
import { DEFAULT_HERO_TYPOGRAPHY } from "@/components/home/heroPresets";

/** Everything a hero template holds except its name and schedule. */
export type HeroTemplateValues = Omit<AdminHeroTemplateInput, "name" | "starts_at" | "ends_at">;

/** Today's hero — the model defaults plus the "Regular" content seeded by migration 0083. */
const REGULAR: HeroTemplateValues = {
  title_prefix: "World",
  title_highlight: "Stories",
  title_highlight_from: "#ed405a",
  title_highlight_to: "#fbbf24",
  description:
    "The home for stories from around the world. Read novels, poetry, and short fiction for free, and discover audiobooks and read-along narrations from authors across every genre and country.",
  ...DEFAULT_HERO_TYPOGRAPHY,
  show_info_lines: true,
  show_stats: true,
  info_line_1_icon: "BookOpenText",
  info_line_1_text: "Full novels, quick reads & poetry",
  info_line_2_icon: "Headphones",
  info_line_2_text: "Audiobooks & read-along narration",
  stat_1_source: "stories",
  stat_1_label: "stories",
  stat_1_value: "",
  stat_2_source: "creators",
  stat_2_label: "creators",
  stat_2_value: "",
  stat_3_source: "readers",
  stat_3_label: "readers",
  stat_3_value: "",
  cta_label: "Start Reading",
  cta_url: "/library",
  cta_bg_from: "#ed405a",
  cta_bg_to: "#f97316",
  cta_text_color: "#ffffff",
  background_color: "#1a212d",
  background_image: "",
  accent_color: "#ed405a",
  animation_preset: "classic",
  animation_icons: [],
};

/**
 * Starting points for a hero template — content, colours and animation that
 * belong together. Applying one only fills in the form; every field stays
 * editable and nothing changes on the site until the template is saved and
 * made default or scheduled.
 */
export const HERO_TEMPLATE_PRESETS: { key: string; label: string; values: HeroTemplateValues }[] = [
  { key: "regular", label: "Regular", values: REGULAR },
  {
    key: "halloween",
    label: "Halloween",
    values: {
      ...REGULAR,
      title_prefix: "Spooky ",
      title_highlight: "Stories",
      title_highlight_from: "#ff7518",
      title_highlight_to: "#a855f7",
      description:
        "Something stirs between the pages. Read ghost stories, folk horror, and eerie legends from every corner of the world for free, then dim the lights and let our audiobooks whisper the tales to you.",
      info_line_1_icon: "Ghost",
      info_line_1_text: "Ghost stories, legends & folk horror",
      info_line_2_icon: "Headphones",
      info_line_2_text: "Haunting audiobooks to hear in the dark",
      cta_label: "Enter if you dare",
      cta_bg_from: "#ff7518",
      cta_bg_to: "#7e22ce",
      background_color: "#120a1f",
      accent_color: "#ff7518",
      animation_preset: "halloween",
      title_font: "Creepster",
      title_weight: 400,
      title_letter_spacing: "wide",
      body_font: "Lora",
    },
  },
  {
    key: "winter",
    label: "Winter holidays",
    values: {
      ...REGULAR,
      title_prefix: "Winter ",
      title_highlight: "Tales",
      title_highlight_from: "#93c5fd",
      title_highlight_to: "#f0f9ff",
      description:
        "Long nights call for good stories. Curl up with fireside folktales, festive classics, and snowbound adventures from around the world, free to read or listen to.",
      info_line_1_icon: "Snowflake",
      info_line_1_text: "Fireside folktales & festive classics",
      info_line_2_icon: "Gift",
      info_line_2_text: "Free audiobooks for cosy evenings",
      cta_label: "Curl up with a story",
      cta_bg_from: "#3b82f6",
      cta_bg_to: "#06b6d4",
      background_color: "#0b1a2e",
      accent_color: "#60a5fa",
      animation_preset: "winter",
      title_font: "Cormorant Garamond",
      title_size: "large",
      title_letter_spacing: "normal",
      body_font: "Lora",
    },
  },
  {
    key: "christmas",
    label: "Christmas",
    values: {
      ...REGULAR,
      title_prefix: "Christmas ",
      title_highlight: "Stories",
      title_highlight_from: "#ef4444",
      title_highlight_to: "#fbbf24",
      description:
        "Gather round for the season's best stories. Festive classics, fireside folktales, and Christmas legends from around the world, free to read and to listen to together.",
      info_line_1_icon: "TreePine",
      info_line_1_text: "Festive classics & Christmas legends",
      info_line_2_icon: "Gift",
      info_line_2_text: "Free audiobooks to share with family",
      cta_label: "Unwrap a story",
      cta_bg_from: "#dc2626",
      cta_bg_to: "#16a34a",
      background_color: "#0d2418",
      accent_color: "#dc2626",
      animation_preset: "christmas",
      title_font: "Mountains of Christmas",
      title_size: "large",
      body_font: "Lora",
    },
  },
  {
    key: "new-year",
    label: "New year",
    values: {
      ...REGULAR,
      title_prefix: "New Year, ",
      title_highlight: "New Stories",
      title_highlight_from: "#facc15",
      title_highlight_to: "#f472b6",
      description:
        "Start the year with a reading resolution you'll actually keep. Fresh stories, new voices, and quick reads you can finish before your coffee cools.",
      info_line_1_icon: "PartyPopper",
      info_line_1_text: "New stories added every week",
      info_line_2_icon: "Clock3",
      info_line_2_text: "Quick reads for busy days",
      cta_label: "Start your reading year",
      cta_bg_from: "#eab308",
      cta_bg_to: "#ec4899",
      background_color: "#14102a",
      accent_color: "#facc15",
      animation_preset: "classic",
      animation_icons: ["Sparkles", "Star", "PartyPopper", "Gem", "Zap"],
      title_font: "Abril Fatface",
      title_weight: 400,
      title_letter_spacing: "normal",
    },
  },
  {
    key: "love",
    label: "Love stories",
    values: {
      ...REGULAR,
      title_prefix: "Love ",
      title_highlight: "Stories",
      title_highlight_from: "#fb7185",
      title_highlight_to: "#fda4af",
      description:
        "Romances, heartbreaks, and love letters from across the world. Fall for a story this season, free to read and listen to.",
      info_line_1_icon: "Heart",
      info_line_1_text: "Romance, poetry & love letters",
      info_line_2_icon: "Headphones",
      info_line_2_text: "Narrated love stories",
      cta_label: "Fall for a story",
      cta_bg_from: "#e11d48",
      cta_bg_to: "#f472b6",
      background_color: "#2a0f1d",
      accent_color: "#f43f5e",
      animation_preset: "classic",
      animation_icons: ["Heart", "Flower2", "Sparkles", "Feather"],
      title_font: "Dancing Script",
      title_size: "large",
      title_letter_spacing: "normal",
      body_font: "Lora",
    },
  },
  {
    key: "summer",
    label: "Summer reading",
    values: {
      ...REGULAR,
      title_prefix: "Summer ",
      title_highlight: "Reads",
      title_highlight_from: "#fbbf24",
      title_highlight_to: "#fb923c",
      description:
        "Adventures for long days and warm nights. Pack a story for the beach, the train, or the hammock, with audiobooks for when your eyes need a break.",
      info_line_1_icon: "Sun",
      info_line_1_text: "Adventures, travel tales & light reads",
      info_line_2_icon: "Headphones",
      info_line_2_text: "Audiobooks for the road",
      cta_label: "Find a summer read",
      cta_bg_from: "#f59e0b",
      cta_bg_to: "#ef4444",
      background_color: "#0f2a2e",
      accent_color: "#fbbf24",
      animation_preset: "classic",
      animation_icons: ["Sun", "Leaf", "Globe2", "BookOpen", "Cloud"],
      title_font: "Pacifico",
      title_weight: 400,
      title_letter_spacing: "normal",
    },
  },
  {
    key: "minimal",
    label: "Minimal (no animation)",
    values: {
      ...REGULAR,
      title_highlight_from: "#e5e7eb",
      title_highlight_to: "#9ca3af",
      show_info_lines: false,
      cta_bg_from: "#ffffff",
      cta_bg_to: "#e5e7eb",
      cta_text_color: "#111827",
      background_color: "#0a0a0a",
      accent_color: "#3f3f46",
      animation_preset: "none",
    },
  },
];
