import { type RouteConfig, route, layout, index } from "@react-router/dev/routes";

export default [
  layout("layouts/DefaultLayout.tsx", [
    index("pages/Index.tsx"),
    route("login", "components/OpenLoginModalRedirect.tsx", { id: "login-redirect" }),
    route("register", "components/OpenLoginModalRedirect.tsx", { id: "register-redirect" }),
    route("library", "pages/Library.tsx"),
    route("originals", "pages/Originals.tsx"),
    route("trending", "routes/trending-redirect.tsx"),
    route("discover", "pages/Discover.tsx"),
    route("story-map", "pages/StoryMap.tsx"),
    // The reader's own country progress. Deliberately a separate route from
    // /story-map, which is the catalogue and stays public — see §5.1.
    route("story-passport", "pages/StoryPassport.tsx"),
    route("audiobooks", "pages/Audiobooks.tsx"),
    route("watch", "pages/Watch.tsx"),
    route("quick-reads", "pages/QuickReads.tsx"),
    route("authors", "pages/Authors.tsx"),
    route("authors/:id", "pages/AuthorDetail.tsx"),
    route("contest", "pages/Contest.tsx"),
    route("search", "pages/Search.tsx"),
    route("publish", "pages/Publish.tsx"),
    route("profile", "pages/Profile.tsx"),
    route("downloads", "pages/Downloads.tsx"),
    route("about", "pages/About.tsx"),
    route("contact", "pages/Contact.tsx"),
    route("privacy", "pages/Privacy.tsx"),
    route("terms", "pages/Terms.tsx"),
    route("blog", "pages/BlogList.tsx"),
    route("blog/:slug", "pages/BlogDetail.tsx"),
    route("story/:slug", "pages/StoryDetail.tsx"),
    route("tags", "pages/TagsIndex.tsx"),
    route("tag/:slug", "pages/TagDetail.tsx"),
    route("themes", "pages/ThemesIndex.tsx"),
    route("theme/:slug", "pages/ThemeDetail.tsx"),
    route("genre/:slug", "pages/GenreDetail.tsx"),
    route("category/:slug", "pages/CategoryDetail.tsx"),
    route("quick-read/:slug", "pages/StorySummary.tsx"),
    route("story/:slug/pdf", "pages/PdfReader.tsx"),
    route("story/:slug/epub", "pages/EpubReader.tsx"),
    route("read/:story_slug/:chapter_slug", "pages/StoryReader.tsx"),
    route("listen/:story_slug/:chapter_slug", "pages/AudiobookPlayer.tsx"),
    route("read-along/:story_slug/:audio_slug", "pages/ReadAlongReader.tsx"),
    // Catch-all for unknown paths inside the default layout.
    route("*", "pages/NotFound.tsx", { id: "default-not-found" }),
  ]),

  route("admin", "layouts/AdminLayout.tsx", [
    route("login", "pages/AdminLogin.tsx"),
    layout("layouts/RequireAdminAuth.tsx", [
      layout("layouts/AdminShellLayout.tsx", [
        index("pages/AdminHome.tsx"),
        route("content", "pages/AdminContent.tsx"),
        route("featured", "pages/AdminFeatured.tsx"),
        route("story-report", "pages/AdminStoryReport.tsx"),
        route("submissions", "pages/AdminSubmissions.tsx"),
        route("analytics", "pages/AdminAnalytics.tsx"),
        route("analytics/content-performance", "pages/AdminContentPerformance.tsx"),
        route("categories", "pages/AdminCategories.tsx"),
        route("genres", "pages/AdminGenres.tsx"),
        route("tags", "pages/AdminTags.tsx"),
        route("themes", "pages/AdminThemes.tsx"),
        route("story-types", "pages/AdminStoryTypes.tsx"),
        route("authors", "pages/AdminAuthors.tsx"),
        route("users", "pages/AdminUsers.tsx"),
        route("ai-settings", "pages/AdminAiSettings.tsx"),
        route("blog", "pages/AdminBlogs.tsx"),
      ]),
    ]),
    route("*", "pages/NotFound.tsx", { id: "admin-not-found" }),
  ]),
] satisfies RouteConfig;
